services:
  cwl-validator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      FLASK_APP: app:create_app
      FLASK_DEBUG: 1
    entrypoint: flask
    command: run --debug --host 0.0.0.0 --port 5000
    volumes:
      - .:/app
