# nixpacks.toml

# Specify the version of Node.js you want to use
[NODE]
version = "20" # replace with your desired Node.js version

# Phases definition
[phases.setup]
commands = [
  "npm install -g pnpm",  # Install pnpm globally
]

[phases.install]
commands = [
  "pnpm install",  # Install project dependencies using pnpm
]

[phases.build]
commands = [
  "pnpm run build",  # Build the application using pnpm
]

# Optionally specify environment variables
[env]
NIXPACKS_NODE_VERSION = "20"  # replace with your desired Node.js version
