version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "${PORT:-3000}:3000"
    environment:
      # Database (external)
      - DATABASE_URL=${DATABASE_URL}
      # Node
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      # Add your custom env variables here
      - CUSTOM_VAR=${CUSTOM_VAR:-default_value}
    env_file:
      - .env
      # You can add additional env files for different environments
      # - .env.${NODE_ENV:-production}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
