name: Deploy to staging environment

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Run script
      #   env:
      #     COOLIFY_API_TOKEN: ${{ secrets.COOLIFY_API_TOKEN }}
      #     BOT_DEPLOY_HOOK: ${{ secrets.STAGING_BOT_DEPLOY_HOOK }}
      #     UI_DEPLOY_HOOK: ${{ secrets.STAGING_UI_DEPLOY_HOOK }}
      #   run: pnpm scripts:deploy
